# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-10 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20160907_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='job_title',
            new_name='industry_or_course',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='url',
            new_name='special_interest_or_SH',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, default='Your Name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media_root/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
