# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-12 13:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0004_remove_userprofile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_educational_institutional_or_schools', models.CharField(max_length=50)),
                ('qualification_level', models.CharField(choices=[('M', 'Masters'), ('B', 'Bachelors'), ('D', 'Diploma'), ('C', 'Certificate')], max_length=50)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('description', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Education Profiles',
            },
        ),
    ]
